//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 16/04/2024 11:50:17 AM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

#nullable enable annotations
#nullable disable warnings

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;
using System.Text.Json.Serialization;

namespace ServerApp
{
    public partial class Usetype {

        public Usetype()
        {
            this.Users = new List<User>();
            OnCreated();
        }

        public Usetype(int id) : this()        {
            this.Id = id;
        }

        public int Id { get; set; }

        public string? Name { get; set; }

        [JsonIgnore]
        public virtual IList<User> Users { get; set; }

        #region Extensibility Method Definitions

        partial void OnCreated();

        #endregion
    }

}
