//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 16/04/2024 11:50:17 AM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

#nullable enable annotations
#nullable disable warnings

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;
using System.Text.Json.Serialization;

namespace ServerApp
{
    public partial class Module {

        public Module()
        {
            this.Operations = new List<Operation>();
            this.Privileges = new List<Privilege>();
            OnCreated();
        }

        public Module(int id) : this()        {
            this.Id = id;
        }

        public int Id { get; set; }

        public string? Name { get; set; }

        [JsonIgnore]
        public virtual IList<Operation> Operations { get; set; }

        [JsonIgnore]
        public virtual IList<Privilege> Privileges { get; set; }

        #region Extensibility Method Definitions

        partial void OnCreated();

        #endregion
    }

}
