//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 16/04/2024 11:50:17 AM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

#nullable enable annotations
#nullable disable warnings

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;

namespace ServerApp
{
    public partial class Privilege {

        public Privilege()
        {
            OnCreated();
        }

        public Privilege(int id) : this()        {
            this.Id = id;
        }

        public int Id { get; set; }

        public string? Authority { get; set; }

        [Required]
        public int ModuleId { get; set; }

        [Required]
        public int OperationId { get; set; }

        [Required]
        public int RoleId { get; set; }

        public virtual Module Module { get; set; }

        public virtual Operation Operation { get; set; }

        public virtual Role Role { get; set; }

        #region Extensibility Method Definitions

        partial void OnCreated();

        #endregion
    }

}
